Add sonar badges into README.md
dial-once/node-phone-utils pull request #29
Opened 2018-04-09 15:46 UTC by steven-heng

2018-04-09 15:53 UTC, jkernech requested changes
You can remove the old badges since they are obsolete

2018-04-10 10:52 UTC, jkernech approved these changes

2018-06-14 13:42 UTC, mrister approved these changes
This is ok but tests seem to be failing which is a separate concern than this PR

2018-07-02 15:57 UTC, jkernech commented
Merging this PR and creating an issue for the tests

2018-07-02 15:57 UTC, merged